events {
    worker_connections 1024;
}

http {

    proxy_headers_hash_max_size 1024;
    proxy_headers_hash_bucket_size 128;

   lua_package_path "/usr/local/openresty/custom-lualib/?.lua;;";

    # Docker's internal DNS resolver
    resolver 127.0.0.11 valid=30s ipv6=off;

    upstream auth-service {
        server auth-service:8081;
    }
    upstream user-service {
         server user-service:8082;
    }

     log_format detailed '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" "$http_user_agent" '
                        'user_id="$http_x_user_id" user_email="$http_x_user_email" user_role="$http_x_user_role"';
    

    server {
        listen 80;
        server_name localhost;

       include  /usr/local/openresty/nginx/conf/services/auth-service.conf;
       include  /usr/local/openresty/nginx/conf/services/user-service.conf;

    }

}