FROM node:18-alpine

WORKDIR /app

COPY services/user-service/ /app

RUN npm install

# Copy shared proto files
COPY shared/libraries/user.proto /app/user.proto

EXPOSE 8082
EXPOSE 50051

# HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=5 \
#   CMD node healthcheck.js

CMD ["npm", "start"] 