location /api/analytics {
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'MANAGER','ADMIN'})
    }
    proxy_pass http://analytics-service/api/analytics;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}
