location /auth-validate {
               #only nginx can call this endpoint
                internal;
                proxy_pass http://auth-service/api/auth/validate;
                proxy_pass_request_body off;
                proxy_set_header Content-Length "";
                proxy_set_header X-Original-URI $request_uri;
                proxy_set_header Authorization $http_authorization;
        }

        #auth service endpoints
location /api/auth/login {
            proxy_pass http://auth-service/api/auth/login;
            include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

location /api/auth/refresh {
            proxy_pass http://auth-service/api/auth/refresh;
            include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
            proxy_set_header Authorization $http_authorization;
        }

location /api/auth/logout {
            proxy_pass http://auth-service/api/auth/logout;
            include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
            proxy_set_header Authorization $http_authorization;
        }