location /api/transaction{
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'CUSTOMER','MANAGER'})
    }
    proxy_pass http://transaction-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}