 #'DEALER', 'MANAGER', 'CUSTOMER', 'ADMIN', 'DELIVERY', 'WAITER'
 
 #user service
location /api/users/register {
proxy_pass http://user-service$request_uri;
include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}

location /api/users {
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'ADMIN'})
    }
    proxy_pass http://user-service;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
    #access_log /usr/local/openresty/nginx/logs/access.log detailed;
}


location ~ ^/api/users/([a-fA-F0-9]+)$ {
    access_by_lua_block {
        local auth = require "auth"
        auth.validate_auth({'CUSTOMER','MANAGER','ADMIN'})
    }
    proxy_pass http://user-service$request_uri;
    include /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}

location /api/users/update {
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'CUSTOMER','MANAGER','ADMIN'})
    }
    proxy_pass http://user-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}


location /api/users/status {
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'ADMIN'})
    }
      proxy_pass http://user-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}


location /api/managers{
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'ADMIN'})
    }
      proxy_pass http://user-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}

location /api/managers/create{
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'ADMIN'})
    }
    proxy_pass http://user-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}

location ~ ^/api/managers/([a-fA-F0-9]+)$ {
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'ADMIN','MANAGER'})
    }
    proxy_pass http://user-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}

location /api/managers/update{
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'ADMIN','MANAGER'})
    }
    proxy_pass http://user-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}

location /api/dealers/create{
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'ADMIN'})
    }
    proxy_pass http://user-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}

location ~ ^/api/dealers/([a-fA-F0-9]+)$ {
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'ADMIN','MANAGER'})
    }
    proxy_pass http://user-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}

location /api/dealers/update{
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'ADMIN','MANAGER'})
    }
    proxy_pass http://user-service$request_uri;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}
