location /api/wallet/balance {
    access_by_lua_block {
    local auth = require "auth"
    auth.validate_auth({'CUSTOMER','MANAGER','ADMIN'})
    }
    proxy_pass http://wallet-service/api/wallet/balance;
    include  /usr/local/openresty/nginx/conf/proxy_header/proxy_headers.conf;
}
