# docker-compose.override.yml

services:

  # 🔁 Auth Service Dev Mode
  auth-service:
    volumes:
      - ../services/auth-service:/app
      - ../shared/libraries/user.proto:/app/user.proto
      - node_modules_auth:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start

  # 🔁 User Service Dev Mode
  user-service:
    volumes:
      - ../services/user-service:/app
      - ../shared/libraries/user.proto:/app/user.proto
      - node_modules_user:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start
  
  order-service:
    volumes:
      - ../services/order-service:/app
      - node_modules_order:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start

  catalogue-service:
    volumes:
      - ../services/catalogue-service:/app
      - node_modules_catalogue:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start

  # 🔁 Redis Dev + Redis Commander
  redis:
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    labels:
      - "traefik.enable=true"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: pos-redis-commander
    hostname: redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - pos-network
    profiles:
      - dev

  # 🔁 User MongoDB Dev
  userMongodb:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db

  # 🔁 Catalogue MongoDB Dev
  catalogue_mongodb:
    ports:
      - "27018:27017"
    volumes:
      - catalogue_mongodb_dev_data:/data/db

  # 🔁 Order MongoDB Dev
  order_mongodb:
    ports:
      - "27019:27017"
    volumes:
      - order_mongodb_dev_data:/data/db

volumes:
  node_modules_gateway:
  node_modules_auth:
  node_modules_user:
  node_modules_order:
  node_modules_catalogue:
  redis_dev_data:
  mongodb_dev_data:
  catalogue_mongodb_dev_data:
  order_mongodb_dev_data: