# docker-compose.override.yml

services:

  ############################
  #        Services          #
  ############################

  # 🔁 Auth Service Dev Mode
  auth-service:
    volumes:
      - ../services/auth-service:/app
      - ../shared/libraries/user.proto:/app/user.proto
      - node_modules_auth:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start

  # 🔁 User Service Dev Mode
  user-service:
    volumes:
      - ../services/user-service:/app
      - ../shared/libraries/user.proto:/app/user.proto
      - node_modules_user:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start

  # 🔁 Order Service Dev Mode
  order-service:
    volumes:
      - ../services/order-service:/app
      - node_modules_order:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start

  # 🔁 Catalogue Service Dev Mode
  catalogue-service:
    volumes:
      - ../services/catalogue-service:/app
      - node_modules_catalogue:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start

  # 🔁 Analytic Service Dev Mode
  analytic-service:
    volumes:
      - ../services/analytic-service:/app
      - node_modules_analytic:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=*
    command: npm start


  ############################
  #        Databases         #
  ############################

  # 🔁 User MongoDB Dev
  userMongodb:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db

  # 🔁 Catalogue MongoDB Dev
  catalogue_mongodb:
    ports:
      - "27018:27018"
    volumes:
      - catalogue_mongodb_dev_data:/data/db
    command: ["mongod", "--port", "27018", "--bind_ip_all"]

  # 🔁 Order MongoDB Dev
  order_mongodb:
    ports:
      - "27019:27019"
    volumes:
      - order_mongodb_dev_data:/data/db
    command: ["mongod", "--port", "27019", "--bind_ip_all"]

  # 🔁 Analytic MongoDB Dev
  analytic_mongodb:
    ports:
      - "27020:27020"
    volumes:
      - analytic_mongodb_dev_data:/data/db
    command: ["mongod", "--port", "27020", "--bind_ip_all"]


  ############################
  #       Other Tools        #
  ############################

  # 🔁 Redis Dev
  redis:
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    labels:
      - "traefik.enable=true"

  # 🔁 Redis Commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: pos-redis-commander
    hostname: redis-commander
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - pos-network
    profiles:
      - dev


############################
#          Volumes         #
############################

volumes:
  node_modules_gateway:
  node_modules_auth:
  node_modules_user:
  node_modules_order:
  node_modules_catalogue:
  node_modules_analytic:
  redis_dev_data:
  mongodb_dev_data:
  catalogue_mongodb_dev_data:
  order_mongodb_dev_data:
  analytic_mongodb_dev_data:
