# Generated by grpc_tools.protoc — do not edit manually.
# Use: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. cashback.proto

import grpc
import cashback_pb2 as cashback__pb2


class CashbackServiceStub(object):
    """Client stub for CashbackService."""

    def __init__(self, channel):
        self.GetCashback = channel.unary_unary(
            '/cashback.CashbackService/GetCashback',
            request_serializer=cashback__pb2.CashbackRequest.SerializeToString,
            response_deserializer=cashback__pb2.CashbackResponse.FromString,
        )


class CashbackServiceServicer(object):
    """Server servicer base class for CashbackService."""

    def GetCashback(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CashbackServiceServicer_to_server(servicer, server):
    from grpc import unary_unary_rpc_method_handler as unary_unary
    from grpc import method_service_handler
    generic_handler = grpc.method_service_handler if hasattr(grpc, 'method_service_handler') else None

    rpc_method_handlers = {
        'GetCashback': grpc.unary_unary_rpc_method_handler(
            servicer.GetCashback,
            request_deserializer=cashback__pb2.CashbackRequest.FromString,
            response_serializer=cashback__pb2.CashbackResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_service_handler(
        rpc_method_handlers) if hasattr(grpc, 'method_service_handler') else \
        grpc.GenericMethodHandler(rpc_method_handlers)

    from grpc import GenericRpcHandler
    server.add_generic_rpc_handlers((
        _GenericMethodHandler('cashback.CashbackService', rpc_method_handlers),
    ))


class _GenericMethodHandler(grpc.ServiceRpcHandlers):
    def __init__(self, service_name, method_handlers):
        self._name = service_name
        self._handlers = method_handlers

    def service_name(self):
        return self._name

    def service(self):
        return self._handlers
